# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven # --> Name of the workflow

on: # --> Events that will trigger the gitHub actions
  push: # --> Event 1
    branches: [ "master" ]
  pull_request: # --> Event 2
    branches: [ "master" ]

jobs: # --> Workflow that will be executed whenever the events are triggered
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # --> Action

    - name: Set up JDK 17 # Name given to the action
      uses: actions/setup-java@v3 # --> Action
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven # --> Name given to the
      run: mvn -B package --file pom.xml # --> Command to be run
